### PR TITLE
multiple minor fixes

### PR DESCRIPTION
**Pull request by cdolfi**
This is a couple of minor fixes to handle the following: 

- Reformatting issues graph on Overview page #70 
- Search bar to dynamically take the first input #97 
- Listing orgs first in search bar outputs #105 
- changing start to home page #96

### CODE REVIEW

**Review by JamesKunstle — APPROVED** [review]
lgtm

**Comment by cdolfi** [comment]
@JamesKunstle was this merged? I got an email but still see this open

**Comment by JamesKunstle** [comment]
@cdolfi It says that mypy failed- just check on your local branch that you pass everything and we'll see.

**Comment by cdolfi** [comment]
@JamesKunstle looks like its passed now, if it looks good to you, merge

**Pull request merged**
