### PR TITLE
added active vs. drifting visualization

### PR DESCRIPTION
**Pull request by JamesKunstle**
Signed-off-by: JamesKunstle <jkunstle@bu.edu>

### CODE REVIEW

**Comment by cdolfi** [comment]
There are some changes needed to make format consistent with all of the graphs 
For this graph and Number of new contributors: (look at other two graphs on overview page for code)

- [ ] Auto select range view pending on what date interval selected, x_r in other graphs
- [ ] Update hover descriptions and format. "count: to "contribution", "value = 10" to "Contributions = 10", "Variable = active" to just "active", edit date for date interval. Look at hover variable in other graphs to see how to handle all of this 
- [ ] interval day to be also histogram/bar chart (step one makes this view doable)

**Comment by cdolfi** [comment]
edit legend to change "variable" to another term or remove completely

**Comment by JamesKunstle** [comment]
@cdolfi Thanks for the feedback in the review, will make those changes. Much appreciated.

**Review by cdolfi — APPROVED** [review]
Approve with condition of additional changes on different PR

**Comment by cdolfi** [comment]
@JamesKunstle was this created into a new issue?

**Pull request merged**
